name: Feature idea
description: Suggest something for the server
labels: [idea]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
      description: What would it help you do?
    validations:
      required: true
